### check server status
GET http://localhost:8080/

### create new todo
POST http://localhost:8080/todos
Content-Type: application/json

{
    "title": "Buy groceries",
    "description": "Milk, Bread, Eggs",
    "completed": false
}

### get all todos
GET http://localhost:8080/todos

### get a specific todo by id
GET http://localhost:8080/todos/1

### update a todo by id
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
    "title": "Learn React and Node.js",
    "description": "Milk, Bread, Eggs, Chips",
    "completed": false
}

### delete a todo by id
DELETE http://localhost:8080/todos/1
